[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solpay = "HZF2gdH6uHJQkYLioXZVGLBinJ2GySXZ7eBN44ti11Us"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
